"""add_xendit_escrow

Revision ID: 0bbfac6226ca
Revises: eb3463e675e3
Create Date: 2026-07-24 21:46:05.526273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0bbfac6226ca'
down_revision: Union[str, Sequence[str], None] = 'eb3463e675e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('xendit_external_id', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('xendit_external_id')
    )
    op.create_table('demand_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('demand_request_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('quantity_kg', sa.Float(), nullable=False),
    sa.Column('price_per_kg', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'PAID', 'EXPIRED', 'FAILED', name='paymentstatus'), nullable=False),
    sa.Column('escrow_status', sa.Enum('NOT_STARTED', 'HELD', 'RELEASED', 'REFUNDED', 'DISPUTED', name='escrowstatus'), nullable=False),
    sa.Column('xendit_invoice_id', sa.String(length=255), nullable=True),
    sa.Column('xendit_invoice_url', sa.String(length=500), nullable=True),
    sa.Column('xendit_external_id', sa.String(length=255), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_received_at', sa.DateTime(), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['demand_request_id'], ['demand_requests.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('xendit_external_id')
    )
    op.add_column('orders', sa.Column('payment_status', sa.Enum('PENDING', 'PAID', 'EXPIRED', 'FAILED', name='paymentstatus'), nullable=True))
    op.add_column('orders', sa.Column('escrow_status', sa.Enum('NOT_STARTED', 'HELD', 'RELEASED', 'REFUNDED', 'DISPUTED', name='escrowstatus'), nullable=True))
    op.add_column('orders', sa.Column('xendit_invoice_id', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('xendit_invoice_url', sa.String(length=500), nullable=True))
    op.add_column('orders', sa.Column('xendit_external_id', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('paid_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('confirmed_received_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('released_at', sa.DateTime(), nullable=True))
    op.alter_column('orders', 'status_updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_unique_constraint(None, 'orders', ['xendit_external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='unique')
    op.alter_column('orders', 'status_updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('orders', 'released_at')
    op.drop_column('orders', 'confirmed_received_at')
    op.drop_column('orders', 'paid_at')
    op.drop_column('orders', 'xendit_external_id')
    op.drop_column('orders', 'xendit_invoice_url')
    op.drop_column('orders', 'xendit_invoice_id')
    op.drop_column('orders', 'escrow_status')
    op.drop_column('orders', 'payment_status')
    op.drop_table('demand_transactions')
    op.drop_table('payment_transactions')
    # ### end Alembic commands ###
