"""add_disbursement_and_bank_details

Revision ID: 15479b117cd1
Revises: 0bbfac6226ca
Create Date: 2026-07-24 23:41:59.760201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15479b117cd1'
down_revision: Union[str, Sequence[str], None] = '0bbfac6226ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demand_transactions', sa.Column('disbursement_id', sa.String(length=255), nullable=True))
    op.add_column('demand_transactions', sa.Column('disbursement_status', sa.String(length=50), nullable=True))
    op.add_column('demand_transactions', sa.Column('disbursed_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('disbursement_id', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('disbursement_status', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('disbursed_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('bank_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('bank_account_number', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('bank_account_holder', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bank_account_holder')
    op.drop_column('users', 'bank_account_number')
    op.drop_column('users', 'bank_name')
    op.drop_column('orders', 'disbursed_at')
    op.drop_column('orders', 'disbursement_status')
    op.drop_column('orders', 'disbursement_id')
    op.drop_column('demand_transactions', 'disbursed_at')
    op.drop_column('demand_transactions', 'disbursement_status')
    op.drop_column('demand_transactions', 'disbursement_id')
    # ### end Alembic commands ###
