"""add demand request and supply commitment

Revision ID: 24ac0d244831
Revises: 694108a246ae
Create Date: 2026-07-14 15:27:26.769496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '24ac0d244831'
down_revision: Union[str, Sequence[str], None] = '694108a246ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demand_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('commodity_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('quantity_kg_needed', sa.Float(), nullable=False),
    sa.Column('quantity_kg_committed', sa.Float(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('TERBUKA', 'TERPENUHI', 'KEDALUWARSA', 'DIBATALKAN', name='demandrequeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supply_commitments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('demand_request_id', sa.UUID(), nullable=False),
    sa.Column('petani_id', sa.UUID(), nullable=False),
    sa.Column('quantity_kg_committed', sa.Float(), nullable=False),
    sa.Column('committed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['demand_request_id'], ['demand_requests.id'], ),
    sa.ForeignKeyConstraint(['petani_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('orders_buyer_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['buyer_id'], ['id'])
    op.drop_constraint(op.f('products_seller_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'users', ['seller_id'], ['id'])
    op.drop_constraint(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_seller_id_fkey'), 'products', 'users', ['seller_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_buyer_id_fkey'), 'orders', 'users', ['buyer_id'], ['id'], ondelete='CASCADE')
    op.drop_table('supply_commitments')
    op.drop_table('demand_requests')
    # ### end Alembic commands ###
