"""add_ratings_and_buyer_confirmation

Revision ID: 2e4ae4c23944
Revises: 9057ce34506b
Create Date: 2026-07-17 16:54:12.191273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e4ae4c23944'
down_revision: Union[str, Sequence[str], None] = '9057ce34506b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rater_id', sa.UUID(), nullable=False),
    sa.Column('rated_id', sa.UUID(), nullable=False),
    sa.Column('role_context', sa.Enum('AS_SELLER', 'AS_BUYER', name='rolecontext'), nullable=False),
    sa.Column('transaction_type', sa.Enum('PRODUCT_PURCHASE', 'DEMAND_FULFILLMENT', name='transactiontype'), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rated_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rater_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rater_id', 'rated_id', 'transaction_type', 'reference_id', name='uq_rater_rated_transaction_ref')
    )
    op.add_column('orders', sa.Column('buyer_confirmed_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('seller_rating_avg', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('seller_rating_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('buyer_rating_avg', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('buyer_rating_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'buyer_rating_count')
    op.drop_column('users', 'buyer_rating_avg')
    op.drop_column('users', 'seller_rating_count')
    op.drop_column('users', 'seller_rating_avg')
    op.drop_column('orders', 'buyer_confirmed_at')
    op.drop_table('ratings')
    # ### end Alembic commands ###
