"""auth: switch to google login

Revision ID: 5c88b6bb6c05
Revises: a095c64e38a0
Create Date: 2026-07-11 21:35:57.166291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
"""auth: switch to google login

Revision ID: 5c88b6bb6c05
Revises: a095c64e38a0
Create Date: 2026-07-11 21:35:57.166291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c88b6bb6c05'
down_revision: Union[str, Sequence[str], None] = 'a095c64e38a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_sub', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('PETANI', 'PEMBELI', 'AGEN', name='userrole'),
               nullable=True)
    op.alter_column('users', 'phone_whatsapp',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=True)
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.alter_column('users', 'phone_whatsapp',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('PETANI', 'PEMBELI', 'AGEN', name='userrole'),
               nullable=False)
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'google_sub')
    # ### end Alembic commands ###
