"""add_embedding_to_demand_requests

Revision ID: 661c1e158f82
Revises: 2e4ae4c23944
Create Date: 2026-07-22 20:59:27.104079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '661c1e158f82'
down_revision: Union[str, Sequence[str], None] = '2e4ae4c23944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demand_requests', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    op.alter_column('demand_requests', 'price_per_kg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('demand_requests', 'price_per_kg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.drop_column('demand_requests', 'embedding')
    # ### end Alembic commands ###
