"""add scraper status table

Revision ID: 694108a246ae
Revises: ef8d472c553e
Create Date: 2026-07-11 21:53:40.755177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add scraper status table

Revision ID: 694108a246ae
Revises: ef8d472c553e
Create Date: 2026-07-11 21:53:40.755177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '694108a246ae'
down_revision: Union[str, Sequence[str], None] = 'ef8d472c553e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraper_statuses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', name='scrapestatusenum'), nullable=False),
    sa.Column('items_scraped', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scraper_statuses')
    # ### end Alembic commands ###
