"""add_chat_models

Revision ID: c94b96552459
Revises: 44c45d37303b
Create Date: 2026-07-29 21:03:39.545889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c94b96552459'
down_revision: Union[str, Sequence[str], None] = '44c45d37303b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('last_product_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
    sa.Column('last_message_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('buyer_id', 'seller_id', name='uq_buyer_seller_conversation')
    )
    op.create_index('idx_conversations_buyer_last_msg', 'conversations', ['buyer_id', 'last_message_at'], unique=False)
    op.create_index('idx_conversations_seller_last_msg', 'conversations', ['seller_id', 'last_message_at'], unique=False)
    op.create_index(op.f('ix_conversations_buyer_id'), 'conversations', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_conversations_last_message_at'), 'conversations', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_conversations_seller_id'), 'conversations', ['seller_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    
    # Manual SQL for RLS policies and Supabase Realtime
    op.execute("ALTER TABLE conversations ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE messages ENABLE ROW LEVEL SECURITY;")

    # Policy SELECT & INSERT in conversations
    op.execute("""
        CREATE POLICY select_conversations ON conversations
        FOR SELECT USING (auth.uid() = buyer_id OR auth.uid() = seller_id);
    """)
    op.execute("""
        CREATE POLICY insert_conversations ON conversations
        FOR INSERT WITH CHECK (auth.uid() = buyer_id OR auth.uid() = seller_id);
    """)
    op.execute("""
        CREATE POLICY update_conversations ON conversations
        FOR UPDATE USING (auth.uid() = buyer_id OR auth.uid() = seller_id);
    """)

    # Policy SELECT & INSERT in messages
    op.execute("""
        CREATE POLICY select_messages ON messages
        FOR SELECT USING (
            EXISTS (
                SELECT 1 FROM conversations
                WHERE conversations.id = messages.conversation_id
                AND (auth.uid() = conversations.buyer_id OR auth.uid() = conversations.seller_id)
            )
        );
    """)
    op.execute("""
        CREATE POLICY insert_messages ON messages
        FOR INSERT WITH CHECK (
            sender_id = auth.uid()
            AND EXISTS (
                SELECT 1 FROM conversations
                WHERE conversations.id = messages.conversation_id
                AND (auth.uid() = conversations.buyer_id OR auth.uid() = conversations.seller_id)
            )
        );
    """)
    op.execute("""
        CREATE POLICY update_messages ON messages
        FOR UPDATE USING (
            EXISTS (
                SELECT 1 FROM conversations
                WHERE conversations.id = messages.conversation_id
                AND (auth.uid() = conversations.buyer_id OR auth.uid() = conversations.seller_id)
            )
        );
    """)

    # Enable Realtime for messages table
    op.execute("ALTER PUBLICATION supabase_realtime ADD TABLE messages;")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER PUBLICATION supabase_realtime DROP TABLE messages;")
    
    op.execute("DROP POLICY IF EXISTS select_messages ON messages;")
    op.execute("DROP POLICY IF EXISTS insert_messages ON messages;")
    op.execute("DROP POLICY IF EXISTS update_messages ON messages;")
    op.execute("DROP POLICY IF EXISTS select_conversations ON conversations;")
    op.execute("DROP POLICY IF EXISTS insert_conversations ON conversations;")
    op.execute("DROP POLICY IF EXISTS update_conversations ON conversations;")
    
    op.execute("ALTER TABLE messages DISABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE conversations DISABLE ROW LEVEL SECURITY;")

    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index('idx_messages_conversation_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversations_seller_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_last_message_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_buyer_id'), table_name='conversations')
    op.drop_index('idx_conversations_seller_last_msg', table_name='conversations')
    op.drop_index('idx_conversations_buyer_last_msg', table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
