"""change embedding dimension to 768 for gemini

Revision ID: ef8d472c553e
Revises: 5c88b6bb6c05
Create Date: 2026-07-11 21:47:57.599299

"""
"""change embedding dimension to 768 for gemini

Revision ID: ef8d472c553e
Revises: 5c88b6bb6c05
Create Date: 2026-07-11 21:47:57.599299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'ef8d472c553e'
down_revision: Union[str, Sequence[str], None] = '5c88b6bb6c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               existing_nullable=True)
    # ### end Alembic commands ###
